---
title       : Coursera Developing Data Products Project Assignment
subtitle    : Goods item price query
author      : RD
job         : looking
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

This is the project assignment for the Coursera Developing Data Product course.

The project is about querying goods item price. User are given three items to choose from, which are:-

1. Lamb
2. Chicken
3. Beef

The table listing of the price based on the item choosen will be displayed.
The average price of the good items based on the city and state will be calculated by the server and will also be displayed.

---

## The Shiny App : Goods Item Price Query

The table listing the price based on the item choosed will be displayed. The table columns are:-

1. Price - price of the goods items
2. City - city of the good items
3. State - state of the goods items
4. Date - date when the data was published

The shiny app can be accessed from <https://ruslandros.shinyapps.io/project/>

---

## Sample Output for Chicken

``` {r, echo=FALSE}
  library(data.table)
  
  runcit <- read.csv("RUNCIT_21_JANUARY_2016.csv")

  data <- subset(runcit, Nama.Varieti=="AYAM PROSES (STANDARD)")

  sort_data <- data[order(-data$Harga.Purata),]
  avg <- round(mean(sort_data$Harga.Purata),2)
  
  #sort_data
  aa <- sort_data[,c(5,7,8,9)]
  
  names(aa) <- c("Average Price", "City", "State", "Date")
  bb <- data.table(aa)
  bb
  
  #plot.new()
  #grid.table(bb)
  
```

---

## Conclusion and references

This is a very simpe app which hopefully fulfilled the project's requirements.

The read me file is here <https://ruslandros.shinyapps.io/readme-goods-price/>, and source code can be found here <https://github.com/ruslandros/dataproducts>.

The data is read from a CSV file which was previously extracted from a live website located at <http://www.fama.gov.my/harga-pasaran-terkini2>
